### ISSUE TITLE
Ачивмент для Победившего Автора в Авторском контенте.

### ISSUE THREAD

**Issue by YellowAwards** [YouComedy/ycm-frontend#1]
"Автор" 
"Вы наполняете сайт авторским контентом, веселя людей и делая их жизнь чуточку лучше! Вы творец и теперь смело можете регистрировать копирайт на свои шутки."
![8001](https://cloud.githubusercontent.com/assets/23374883/20168399/0f30b944-a733-11e6-8fc4-102fd0405efc.png)

Эта ачивка предоставляется всем номинированным авторам и авторам выбранным позже.

**Comment by slmgc** [comment]
@YellowAwards еще нужно будет обновить файл спрайтов с беджами:
http://static.youcomedy.me/common/img/profile/badges/badges.png

Новый можно будет добавить куда-нибудь в конец списка с такими же отступами:
![screen shot 2016-11-10 at 12 07 02](https://cloud.githubusercontent.com/assets/5236786/20170692/52ae32ae-a73e-11e6-8bf3-32a0eddf07db.png)

Можешь обновленный файл прикрепить сюда же?

**Comment by YellowAwards** [comment]
![badges](https://cloud.githubusercontent.com/assets/23374883/20171111/488a05a8-a740-11e6-8935-15213250c6ca.png)

**Comment by slmgc** [comment]
@antonygorin вот пользователи, которым нужно добавить новый бедж 9000:

http://youcomedy.me/user/sibrusich
http://youcomedy.me/user/kamlot08
http://youcomedy.me/user/goloub_evan
http://youcomedy.me/user/zerpico
http://youcomedy.me/user/mzkarlik
http://youcomedy.me/user/PaveLShubin
http://youcomedy.me/user/Demencat
http://youcomedy.me/user/NeTotoro
http://youcomedy.me/user/hiverv
http://youcomedy.me/user/morfy

**Comment by slmgc** [comment]
@YellowAwards бедж добавлен.

**Comment by YellowAwards** [comment]
http://youcomedy.me/user/sibrusich
http://youcomedy.me/user/kamlot08
http://youcomedy.me/user/goloub_evan
http://youcomedy.me/user/zerpico
http://youcomedy.me/user/mzkarlik
http://youcomedy.me/user/PaveLShubin
http://youcomedy.me/user/Demencat
http://youcomedy.me/user/NeTotoro
http://youcomedy.me/user/hiverv
